[build]
  base = "/"
  publish = "public"  # Adjust this to the directory containing your static files (e.g., HTML, CSS, JS)
  # No build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
